default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mydb

staging:
  <<: *default
  database: mydb

test:
  <<: *default
  database: mydb_test

production:
  <<: *default
  database: mydb
  username: Onich
  password: 12345678
  host: db-1.cij3jdtm0wjb.us-east-2.rds.amazonaws.com
  port: 5432
